import assert from 'node:assert/strict';
import {displayState,hookConfirmation,runtimeConfirmation,CONFIRMATION_TTL} from '../src/health.mjs';
import {reconcileRuntime,runtimeCandidates,selectRuntime} from '../src/runtime.mjs';
const id='00000000-0000-4000-8000-000000000001',turn='00000000-0000-4000-8000-000000000002',nextTurn='00000000-0000-4000-8000-000000000003';
const old={sessionId:id,turnId:turn,status:'aguardando_resposta',at:10,questionPending:true,questionToolId:'q',approvalPending:false};
assert.equal(displayState(old,null,20).displayStatus,'nao_confirmado');
assert.equal(old.status,'aguardando_resposta');assert.equal(old.questionPending,true);
const hook=hookConfirmation(null,old,{subagent:false,event:'PreToolUse',question:true},20);
assert.equal(displayState(old,hook,20).displayStatus,'aguardando_resposta');
assert.equal(displayState(old,hook,20+CONFIRMATION_TTL+1).displayStatus,'nao_confirmado','Age is freshness, never completion.');
assert.equal(hookConfirmation(old,{...old,at:30},{subagent:false,event:'PreToolUse',question:false}),null,'Independent work does not renew an unanswered question.');
const missing={sessionId:id,turnId:turn,type:'active',flags:[],turnStatus:'inProgress',at:40,questionToolId:'q',questionResolved:false,questionPresent:false};
const unchanged=reconcileRuntime(old,missing);assert.equal(unchanged.questionPending,true);
const unknown=runtimeConfirmation(unchanged,missing,41);
assert.equal(displayState(unchanged,{...hook,...unknown},41).displayStatus,'nao_confirmado','A compacted question cannot be displayed as confirmed.');
const realPending={...missing,questionPresent:true};
assert.equal(displayState(unchanged,runtimeConfirmation(unchanged,realPending,42),42).displayStatus,'aguardando_resposta');
const replied={...realPending,at:43,questionResolved:true};const resumed=reconcileRuntime(unchanged,replied);
assert.equal(resumed.status,'processando');assert.equal(resumed.questionPending,false);
assert.equal(displayState(resumed,{...unknown,...runtimeConfirmation(resumed,replied,44)},44).displayStatus,'processando','Successful verification clears uncertainty.');
const newRun=reconcileRuntime(old,{...missing,turnId:nextTurn,currentTurn:true});
assert.equal(newRun.turnId,nextTurn);assert.equal(newRun.status,'processando');assert.ok(newRun.retiredTurns.includes(turn));
assert.equal(reconcileRuntime(newRun,{...missing,at:50,currentTurn:true}),newRun,'Retired snapshots cannot reappear.');
const one={pipe:'\\\\.\\pipe\\fake',threadId:id,turnId:turn};assert.equal(runtimeCandidates(id,[one]).length,1,'Single linked chat can use its own metadata read.');
const result={success:true,contentItems:[{type:'inputText',text:JSON.stringify({thread:{id,hostId:'local',status:{type:'active',activeFlags:[]}},turns:[{id:turn,status:'inProgress',items:[{id:'compact',type:'contextCompaction',text:'PRIVATE_MUST_NOT_PERSIST'}]}]})}]};
const rows=selectRuntime(result,[id],60,{metadata:true,questionToolId:'q'});assert.equal(rows[0].questionPresent,false);assert.equal(rows[0].currentTurn,true);assert.ok(!JSON.stringify(rows).includes('PRIVATE'));
console.log('PASS: unknown display, expiry without inferred completion, compacted IDs, verified recovery, single-chat metadata and missed-turn protection.');
