import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {bridgeFromHook,validBridge,selectRuntime,queryRuntime,reconcileRuntime,runtimePlans} from '../src/runtime.mjs';
import {reduceState} from '../src/state.mjs';
const id='00000000-0000-4000-8000-000000000001',turn='00000000-0000-4000-8000-000000000002',other='00000000-0000-4000-8000-000000000003';
const bridge={pipe:'\\\\.\\pipe\\codex-test',threadId:other,turnId:turn};
assert.ok(validBridge(bridge));assert.ok(!validBridge({...bridge,pipe:'\\\\remote\\pipe\\test'}));
assert.equal(bridgeFromHook({sessionId:id,turnId:turn,subagent:true},{CODEX_APP_TOOLS_PIPE_PATH:bridge.pipe}),null);
assert.deepEqual(bridgeFromHook({sessionId:other,turnId:turn,subagent:false},{CODEX_APP_TOOLS_PIPE_PATH:bridge.pipe}),bridge);
assert.deepEqual(runtimePlans([id,other],[bridge]),[{bridge,ids:[id]}]);
const second={...bridge,threadId:id};
assert.deepEqual(runtimePlans([id,other],[bridge,second]),[{bridge,ids:[id]},{bridge:second,ids:[other]}]);
assert.ok(runtimePlans([id,other,turn],[bridge,second]).every(plan=>plan.ids.length===1),'A ready target must not hide the others.');
assert.deepEqual(await queryRuntime(bridge,[other],{connect:()=>{throw Error('must not call self');}}),[]);
const question=reduceState(undefined,{sessionId:id,turnId:turn,event:'PreToolUse',at:10,subagent:false,question:true,asyncQuestion:true,toolId:'question'});
const working=reduceState(question,{sessionId:id,turnId:turn,event:'PreToolUse',at:11,subagent:false,tool:'exec',toolId:'independent-work'});
assert.equal(working.status,'aguardando_resposta','Independent tools cannot prove a human reply.');
const snapshot={sessionId:id,turnId:turn,type:'active',flags:['waitingOnUserInput'],turnStatus:'inProgress',at:12};
assert.equal(reconcileRuntime(working,snapshot).status,'aguardando_resposta');
assert.equal(reconcileRuntime(working,{...snapshot,flags:[]}).status,'aguardando_resposta','An active agent can still have an unanswered question.');
const resumed=reconcileRuntime(working,{...snapshot,flags:[],questionResolved:true,questionToolId:'question'});
assert.equal(resumed.status,'processando');assert.equal(resumed.questionPending,false);
assert.equal(reconcileRuntime(resumed,{...snapshot,at:13,flags:['waitingOnApproval'],approvalReviewer:'user'}).status,'aguardando_aprovacao');
assert.equal(reconcileRuntime(resumed,{...snapshot,at:13,flags:['waitingOnApproval'],approvalReviewer:'auto_review'}).status,'processando');
assert.equal(reconcileRuntime(resumed,{...snapshot,at:13,flags:['waitingOnApproval']}).status,'sem_sinal');
assert.equal(reconcileRuntime(question,{...snapshot,type:'idle',turnStatus:'completed',flags:[],questionResolved:true,questionToolId:'question'}).status,'respondido');
assert.equal(reconcileRuntime(question,{...snapshot,type:'idle',turnStatus:'completed',flags:[]}).status,'aguardando_resposta');
assert.equal(reconcileRuntime(resumed,{...snapshot,type:'idle',turnStatus:'interrupted',flags:[]}).status,'interrompido');
assert.equal(reconcileRuntime(resumed,{...snapshot,type:'idle',turnStatus:'failed',flags:[]}).status,'sem_sinal');
assert.equal(reconcileRuntime(working,{...snapshot,at:9,flags:[]}),working,'Stale snapshot cannot override a newer hook.');
assert.equal(reconcileRuntime(working,{...snapshot,turnId:other,flags:[]}),working,'Other turns cannot replace the anchored run.');
assert.equal(reconcileRuntime(working,{...snapshot,type:'notLoaded'}),working,'An unloaded chat does not prove completion.');
const poll={thread:{id,hostId:'local',status:{type:'active',activeFlags:[]}},latestTurn:{id:turn,status:'inProgress'},latestAssistantMessage:{text:'PRIVATE_RESPONSE'},latestToolMarker:{arguments:'PRIVATE_ARGUMENT'}};
const result={success:true,contentItems:[{type:'inputText',text:JSON.stringify({polls:[poll,{...poll,thread:{...poll.thread,id:other}}]})}]};
const selected=selectRuntime(result,[id],20);
assert.deepEqual(selected,[{...snapshot,flags:[],at:20}]);assert.ok(!JSON.stringify(selected).includes('PRIVATE'));
assert.deepEqual(selectRuntime({...result,success:false},[id],20),[]);
const metadata={thread:{id,hostId:'local',status:{type:'active',activeFlags:[]}},turns:[{id:turn,status:'inProgress',items:[{type:'agentMessage',id:'question',text:'PRIVATE_QUESTION'},{type:'userMessage',id:'reply',content:'PRIVATE_REPLY'}]}]};
const readResult=body=>({success:true,contentItems:[{type:'inputText',text:JSON.stringify(body)}]});
const replied=selectRuntime(readResult(metadata),[id],20,{questionToolId:'question'})[0];
assert.equal(replied.questionResolved,true);assert.ok(!JSON.stringify(replied).includes('PRIVATE'));
assert.equal(selectRuntime(readResult({...metadata,turns:[{...metadata.turns[0],items:metadata.turns[0].items.slice(0,1)}]}),[id],20,{questionToolId:'question'})[0].questionResolved,false);
assert.equal(selectRuntime(readResult({...metadata,turns:[{...metadata.turns[0],items:[{type:'contextCompaction',id:'compact'}]}]}),[id],20,{questionToolId:'question'})[0].questionResolved,false,'Compaction does not prove a reply.');
assert.deepEqual(selectRuntime({success:true,contentItems:[{type:'inputText',text:'invalid'}]},[id],20),[]);
assert.deepEqual(selectRuntime({success:true,contentItems:[{type:'inputText',text:JSON.stringify({polls:[{...poll,thread:{...poll.thread,status:{type:'active',activeFlags:['futureFlag']}}}]})}]},[id],20),[]);
let destroyed=false,request;
function connect(){
 const socket=new EventEmitter();socket.destroy=()=>{destroyed=true;};
 socket.write=frame=>{
  assert.equal(frame.readUInt32LE(0),frame.length-4);request=JSON.parse(frame.subarray(4));
  const payload=Buffer.from(JSON.stringify({jsonrpc:'2.0',id:1,result})),response=Buffer.alloc(payload.length+4);response.writeUInt32LE(payload.length);payload.copy(response,4);
  queueMicrotask(()=>{socket.emit('data',response.subarray(0,3));socket.emit('data',response.subarray(3,9));socket.emit('data',response.subarray(9));});
 };
 queueMicrotask(()=>socket.emit('connect'));return socket;
}
assert.deepEqual(await queryRuntime(bridge,[id],{connect,now:()=>20}),selected);
assert.equal(request.method,'tools/call');assert.equal(request.params.tool,'wait_threads');assert.equal(request.params.arguments.timeoutMs,0);
assert.deepEqual(request.params.arguments.targets,[{threadId:id,hostId:'local'}]);assert.ok(destroyed);
assert.deepEqual(await queryRuntime(bridge,[id],{connect:()=>{throw Error('closed');}}),[]);
assert.deepEqual(await queryRuntime(bridge,[id],{timeoutMs:5,connect:()=>{const socket=new EventEmitter();socket.destroy=()=>{};return socket;}}),[]);
console.log('PASS: same-turn replies, genuine pending requests, turn ordering, metadata privacy and desktop bridge framing/failure.');
